"""add artifact identifier

Revision ID: 63a9f027bd8e
Revises: f2321be6f3e5
Create Date: 2022-02-23 11:25:51.889055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a9f027bd8e'
down_revision = 'f2321be6f3e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artifact', sa.Column('identifier', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artifact', 'identifier')
    # ### end Alembic commands ###
