"""add theme db models

Revision ID: 73b7df31ada5
Revises: 63a9f027bd8e
Create Date: 2022-02-25 17:57:32.834273

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '73b7df31ada5'
down_revision = '63a9f027bd8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Theme',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.Text(), nullable=True),
                    sa.Column('theme', sa.Text(), nullable=False),
                    sa.Column('theme_description', sa.Text(), nullable=True),
                    sa.Column('update_count', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('theme'))

    with op.batch_alter_table("Label") as batch_op:
        batch_op.add_column(sa.Column('theme_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("LabelThemeFK", 'Theme', ['theme_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Label', type_='foreignkey')
    op.drop_column('Label', 'theme_id')
    op.drop_table('Theme')
    # ### end Alembic commands ###
