"""added artifact labeling count

Revision ID: 83c3b82ea803
Revises: bee073db4c51
Create Date: 2022-02-14 14:37:26.104933

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '83c3b82ea803'
down_revision = 'bee073db4c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ArtifactLabelRelation', sa.Column('label_update_count', sa.Integer(), nullable=True))
    op.execute('update ArtifactLabelRelation set label_update_count = 1')

    with op.batch_alter_table("ArtifactLabelRelation") as batch_op:
        batch_op.alter_column('label_update_count', nullable=False, default=1)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ArtifactLabelRelation', 'label_update_count')
    # ### end Alembic commands ###
