"""added artifact labeling count

Revision ID: 83c3b82ea803
Revises: bee073db4c51
Create Date: 2022-02-14 14:37:26.104933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c3b82ea803'
down_revision = 'bee073db4c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ArtifactLabelRelation', sa.Column('label_update_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ArtifactLabelRelation', 'label_update_count')
    # ### end Alembic commands ###
