"""manual upload artifact flag

Revision ID: b3a5f0a9003e
Revises: 63a9f027bd8e
Create Date: 2022-03-01 10:46:07.630329

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b3a5f0a9003e'
down_revision = '63a9f027bd8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artifact', sa.Column('uploaded_manually', sa.Boolean(), nullable=True))
    op.execute('update Artifact set uploaded_manually=FALSE;')

    with op.batch_alter_table("Artifact") as batch_op:
        batch_op.alter_column('uploaded_manually', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artifact', 'uploaded_manually')
    # ### end Alembic commands ###
