"""description for each label

Revision ID: f2321be6f3e5
Revises: 83c3b82ea803
Create Date: 2022-02-17 19:17:09.417982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2321be6f3e5'
down_revision = '83c3b82ea803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Label', sa.Column('label_description', sa.Text(), nullable=True))
    op.drop_column('Label', 'remark')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Label', sa.Column('remark', sa.TEXT(), nullable=True))
    op.drop_column('Label', 'label_description')
    # ### end Alembic commands ###
