"""description for each label

Revision ID: f2321be6f3e5
Revises: 83c3b82ea803
Create Date: 2022-02-17 19:17:09.417982

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f2321be6f3e5'
down_revision = '83c3b82ea803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Label") as batch_op:
        batch_op.add_column(sa.Column('label_description', sa.Text(), nullable=True))
        batch_op.drop_column('remark')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Label") as batch_op:
        batch_op.add_column(sa.Column('remark', sa.TEXT(), nullable=True))
        batch_op.drop_column('label_description')
    # ### end Alembic commands ###
